spring.application.name=Workflow
server.port=8082

# Base de datos (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=disable
spring.datasource.username=postgres.qpxuitwzfltkfoxbxoke
spring.datasource.password=Pr0jectSigmur!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase JWT
supabase.jwt.secret=TU_JWT_SECRET
jwt.expiration=86400000

